hrproj/hr/models.py
from datetime import datetime
import re
from threading import Thread
from Queue import Queue

from django.contrib.auth.models import User
from django.db import models, transaction

from hrproj.lib import amazon

NO_VALUE = object()

def calc_slug(name):
    """ Calculates a slug from a name.
    """
    no_spaces = re.sub(r"\s+", "-", name.lower())
    return re.sub(r"[^-\w]", "", no_spaces)[:50]

class Tag(models.Model):
    name = models.CharField(maxlength=200, unique=True)
    slug = models.SlugField(prepopulate_from=('name',), unique=True)

    class Admin:
        pass

    class Meta:
        ordering = ('name',)

    def get_absolute_url(self):
        return "/tags/%s/" % self.slug

    def save(self):
        """ Ensures the slug is set.
        """
        if self.name and not self.slug:
            self.slug = calc_slug(self.name)
        return super(Tag, self).save()

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(maxlength=200)
    author = models.CharField(maxlength=200)
    isbn = models.CharField('ISBN', maxlength=15)
    summary = models.TextField(maxlength=2000)
    tags = models.ManyToManyField(Tag, blank=True)
    slug = models.SlugField(prepopulate_from=('title',), unique=True)
    amazon_checked = models.DateTimeField(null=True, blank=True)
    amazon_small_url = models.URLField(null=True, blank=True)
    amazon_large_url = models.URLField(null=True, blank=True)
    amazon_buy_url = models.URLField(null=True, blank=True)

    __most_recent = NO_VALUE

    class Admin:
        list_display = ('title', 'author')
        fields = (
            (None, {
                'fields': ('title', 'author', 'isbn', 'tags', 'summary')
            }),
            ('Advanced', {
                'classes': 'collapse',
                'fields': ('slug', 'amazon_checked', 'amazon_small_url',
                    'amazon_large_url', 'amazon_buy_url')
            }),
        )

    class Meta:
        ordering = ('author', 'title')

    def fetch_amazon_data(self):
        """ Fetch amazon data for this book
        """
        try:
            result = amazon.searchByASIN(self.isbn)[0]
            self.amazon_buy_url = result.URL
            self.amazon_small_url = result.ImageUrlSmall
            self.amazon_large_url = result.ImageUrlLarge
            self.amazon_checked = datetime.now()
            print "Data retrieved OK"
        except amazon.AmazonError, e:
            print "Amazon i/f returned error: %s" % e

    def get_absolute_url(self):
        return "/books/%s/" % self.slug

    @property 
    def most_recent(self):
        """ Gets most recent reading occasion, if there is one.
        """

        if self.__most_recent == NO_VALUE:
            self.__most_recent = None
            ro_list = ReadingOccasion.objects.filter(book=self.id).order_by('-finished')
            if ro_list.count():
                self.__most_recent = ro_list[0]
        return self.__most_recent

    def save(self):
        """ Ensures the slug is set.
        """
        if self.title and not self.slug:
            self.slug = calc_slug(self.title)
        if self.should_check_amazon:
            self.fetch_amazon_data()
        super(Book, self).save()

    @property
    def should_check_amazon(self):
        """ Whether a check of Amazon is required. 
        """
        if not self.amazon_checked:
            return True
        interval = datetime.now() - self.amazon_checked
        print interval.days
        return interval.days >= 1

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


class Reader(models.Model):
    user = models.ForeignKey(User, edit_inline=models.STACKED, max_num_in_admin=1)
    bio = models.TextField(core=True, maxlength=2000)
    picture = models.ImageField(upload_to="photos/%Y%m%d", blank=True)

    __most_recent = NO_VALUE

    def get_absolute_url(self):
        return "/readers/%s/" % self.user.username

    @property 
    def most_recent(self):
        """ Gets most recent reading occasion, if there is one.
        """
        if self.__most_recent == NO_VALUE:
            self.__most_recent = None
            ro_list = ReadingOccasion.objects.filter(reader=self.id).order_by('-finished')
            if ro_list.count():
                self.__most_recent = ro_list[0]
        return self.__most_recent
    
    @property
    def name(self):
        return self.user.get_full_name()

    def __str__(self):
        return self.user.get_full_name() or self.user.username


class ReadingOccasion(models.Model):
    reader = models.ForeignKey(Reader)
    book = models.ForeignKey(Book, edit_inline=models.STACKED, num_in_admin=1)
    finished = models.DateField(core=True)
    reading_time = models.FloatField(core=True, max_digits=5, decimal_places=2, blank=True)
    notes = models.TextField(maxlength=2000, blank=True)


hrproj/hr/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
{% load hr_tags %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title>Habitual Readers</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<meta name="description" content="description goes here" />
<meta name="keywords" content="keywords,goes,here" />
<link rel="stylesheet" href="/static/styles/andreas07.css" type="text/css" />
<!--[if IE 6]>
<link rel="stylesheet" href="/static/styles/fix.css" type="text/css" />
<![endif]-->
<link rel="stylesheet" href="/static/styles/custom.css" type="text/css" />
</head>

<body>
<div id="sidebar">
<h1>Habitual Readers</h1>
<h2>What are you reading, toady?</h2>


<div id="menu">
    {% menuitem / Home %}
    {% menuitem /tags/ Tags %}
    {% menuitem /books/ Books %}
    {% menuitem /readers/ Readers %}
    {% menuitem /admin/ Admin %}
</div>

<h3>Version info:</h3>
<p>v1.0 - December 2006</p>
</div>

<div id="content">
<img src="/static/styles/img/red_logo.jpg" />

{% block content %}
Content here.
{% endblock %}

<div id="site_info">Copyright &copy; 2006 Ben Askins and Alan Green. Based on a design by <a href="http://andreasviklund.com">Andreas Viklund</a>.</div>
</div>
</body>
</html>

hrproj/hr/templates/book_detail.html
{% extends "base.html" %}

{% block content %}

<h3>{{ book.title }}</h3>

{% if user.is_authenticated %}
<p>Hi {{ user.get_full_name }}. Would you like to <a href="/admin/hr/book/{{ book.id }}/">change this book</a>?</p>
{% endif %}

{% if book.amazon_large_url %}
    <div class="cover"><img src="{{ book.amazon_large_url }}" /></div>
{% else %}
    {% if book.amazon_small_url %}
        <div class="cover"><img src="{{ book.amazon_small_url }}" /></div>
    {% endif %}
{% endif %}

<p class="byline">{{ book.author }}. (ISBN: 
    {% if book.amazon_buy_url %}
        <a href="{{ book.amazon_buy_url }}">{{ book.isbn }}</a>
    {% else %}
        {{ book.isbn }}
    {% endif %}
)</p>

<p><em>{{ book.summary }}</em> 
    {% if book.amazon_buy_url %}
        (<a href="{{ book.amazon_buy_url }}">Buy this book</a>)
    {% endif %}
</p>


<h4>tags</h4>
<p>
        {% for t in book.tags.all %}
        {% if not forloop.first %}/{% endif %}
            <a href="{{ t.get_absolute_url }}">{{ t.name }}</a> 
        {% endfor %}
</p>


<h4>readings</h4>

<table>
<thead>
<tr>
    <th>Last read by</th>
    <th>When</th>
    <th>Hours</th>
    <th>Notes</th>
</tr>
</thead>
<tbody>
{% for ro in readingoccasion_list %}
<tr>
    <td class="name_col"><a href="{{ ro.reader.get_absolute_url }}">{{ ro.reader.name }}</a></td>
    <td class="date_col">{{ ro.finished|date:"j M Y" }}</td>
    <td class="num_col">{{ ro.reading_time }}</td>
    <td>{% firstof ro.notes "-" %}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% include "frag_next_prev.html" %}
{% endblock %}

hrproj/hr/templates/book_list.html
{% extends "base.html" %}
{% load hr_tags %}

{% block content %}
<h3>all books</h3>

{% if user.is_authenticated %}
<p>Hi {{ user.get_full_name }}. Would you like to <a href="/admin/hr/book/add/">add a new book</a>?</p>
{% endif %}

<table>
<thead>
<tr>
    {% if user.is_authenticated %}
        <th>Actions</th>
    {% endif %}
    <th>&nbsp;</th>
    <th>Book</th>
    <th>Tags</th>
</tr>
</thead>
<tbody>
<tr>
{% for b in book_list %}
<tr>
    {% if user.is_authenticated %}
        <td>
            <a href="/admin/hr/book/{{ b.id }}/">Edit</a>
        </td>
    {% endif %}
    <td class="thumb_col">
        {% if b.amazon_small_url %}
            <a href="{{ b.amazon_buy_url }}"><img src="{{ b.amazon_small_url }}"></a>
        {% else %}
            Image not available
        {% endif %}
    </td>
    <td><a href="{{ b.get_absolute_url }}">{{ b.title }}</a></td>
    <td>
        {% if not b.tags.count %}&nbsp;{% endif %}
        {% for t in b.tags.all %}
        {% if not forloop.first %}/{% endif %}
            <a href="{{ t.get_absolute_url }}">{{ t.name }}</a> 
        {% endfor %}
    </td>
</tr>
{% endfor %}
</tr>
</tbody>
</table>

{% include "frag_next_prev.html" %}
{% endblock %}


hrproj/hr/templates/frag_next_prev.html
{% if is_paginated %}
    {% if has_previous %}
        <form method="GET" action="">
        <input type="hidden" name="page" value="{{ previous }}" />
        <button class="page_button on_left" type="submit" name="prev">&lt;&lt; Prev page</button>
        </form>
    {% endif %}
    {% if has_next %}
        <form method="GET" action="">
        <input type="hidden" name="page" value="{{ next }}" />
        <button class="page_button on_right" type="submit" name="next">Next page &gt;&gt;</button>
        </form>
    {% endif %}

{% endif %}

hrproj/hr/templates/index.html
{% extends "base.html" %}

{% block content %}
<h3>recent reads</h3>


<table>
<thead>
<tr>
    <th>Who</th>
    <th>What</th>
    <th>When</th>
</tr>
</thead>
<tbody>
    {% for read_occ in read_occs %}
<tr>
    <td class="name_col">
        <a href="{{ read_occ.reader.get_absolute_url }}">{{ read_occ.reader.name }}</a>
    </th>
    <td><a href="{{ read_occ.book.get_absolute_url }}">{{ read_occ.book.title }}</a></td>
    <td class="date_col">{{ read_occ.finished|date:"j M Y" }}</td>
</tr>
    {% endfor %}
</tbody>
</table>

<h3>categories</h3>


<p class="taglist">
{% for tag in tags %}
<a class="level_{{ tag.pop_level }}" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
{% endfor %}
</p>

<h3>about us</h3>
<p><strong>Habitual Readers</strong> meet at the Upper Gumtree community hall, 9:30am on the first and third Tuesday of each month. New members are always welcome.</p>

<p>We read so much, we sometimes forget who has read what. We use this website to helps us remember.</p>
{% endblock %}

hrproj/hr/templates/reader_detail.html
{% extends "base.html" %}

{% block content %}
<h3>{{ reader.user.username }}</h3>

{% if user.is_authenticated %}
<p>Hi {{ user.get_full_name }}. Would you like to <a href="/admin/auth/user/{{ reader.user.id }}/">change this reader</a>?</p>
{% endif %}

{% if reader.get_picture_url %}
<img class="reader_picture" src="{{ reader.get_picture_url }}" />
{% endif %}

<p>Full name: <strong>{{ reader.name }}</strong><br />
Total recorded reads: <strong>{{ reader.readingoccasion_set.count }}</strong></p>

<p class="bio">{{ reader.bio }}</p>

<table>
<thead>
<tr>
    <th>Book</th>
    <th>Date</th>
    <th>Hours</th>
    <th>Notes</th>
</tr>
</thead>
<tbody>

{% for ro in readingoccasion_list %}
    <tr>
        <td class="name_col"><a href="{{ ro.book.get_absolute_url }}">{{ ro.book.title }}</a></td>
        <td class="date_col">{{ ro.finished|date:"j M Y" }}</td>
        <td class="num_col">{{ ro.reading_time }}</td>
        <td>{% firstof ro.notes "-" %}</td>
    </tr>
{% endfor %}

</tbody>
</table>

{% include "frag_next_prev.html" %}
{% endblock %}

hrproj/hr/templates/reader_list.html
{% extends "base.html" %}

{% block content %}
<h3>all readers</h3>

{% if user.is_authenticated %}
<p>Hi {{ user.get_full_name }}. Would you like to <a href="/admin/auth/user/add/">add a new reader</a>?</p>
{% endif %}

<table>
<thead>
<tr>
    {% if user.is_authenticated %}
        <th>Actions</th>
    {% endif %}
    <th>Who</th>
    <th># read</th>
    <th>Last Book</th>
    <th>Date</th>
</tr>
</thead>
<tbody>


{% for r in reader_list %}
<tr>
    {% if user.is_authenticated %}
        <td>
            <a href="/admin/auth/user/{{ r.user.id }}/">Edit</a>
        </td>
    {% endif %}
    <td class="name_col"><a href="{{ r.get_absolute_url }}">{{ r.name }}</a></th>
    <td class="num_col">{{ r.readingoccasion_set.count }}</td>
    {% if r.most_recent %} 
        <td>
            <a href="{{ r.most_recent.book.get_absolute_url }}">{{ r.most_recent.book.title }}</a> 
        </td>
        <td class="date_col">
            {{ r.most_recent.finished|date:"j M Y" }}
        </td>
    {% else %}
        <td> - </td>
        <td class="date_col"> - </td>
    {% endif %}
</tr>
{% endfor %}

</tbody>
</table>

{% include "frag_next_prev.html" %}
{% endblock %}

hrproj/hr/templates/tag_detail.html
{% extends "base.html" %}
{% load hr_tags %}

{% block content %}

<h3>{{ tag.name }} books</h3>

{% if user.is_authenticated %}
<p>Hi {{ user.get_full_name }}. Would you like to <a href="/admin/hr/tag/{{ tag.id }}/">change this tag</a>?</p>
{% endif %}

<table>
<thead>
<tr>
    <th>Book</th>
    <th># reads</th>
    <th>Last read by</th>
    <th>When</th>
</tr>
</thead>

<tbody>
{% for b in book_list %}
<tr>
    <td><a href="{{ b.get_absolute_url }}">{{ b.title }}</a></td>
    <td class="num_col">{{ b.readingoccasion_set.count }}</td>
    {% if b.most_recent %}
        <td class="name_col">
            <a href="{{ b.most_recent.reader.get_absolute_url }}">{{ b.most_recent.reader.name }}</a>
        </td>
        <td class="date_col">
            {{ b.most_recent.finished|date:"j M Y" }}
        </td>
    {% else %}
        <td class="name_col"> - </td>
        <td class="date_col"> - </td>
    {% endif %}
</tr>
{% endfor %}

</tbody>
</table>

{% include "frag_next_prev.html" %}
{% endblock %}

hrproj/hr/templates/tag_list.html
{% extends "base.html" %}

{% block content %}
<h3>all tags</h3>

{% if user.is_authenticated %}
<p>Hi {{ user.get_full_name }}. Would you like to <a href="/admin/hr/tag/add/">add a new tag</a>?</p>
{% endif %}

<table>
<thead>
<tr>
    {% if user.is_authenticated %}
        <th>Actions</th>
    {% endif %}
    <th>Tag</th>
    <th>Books</th>
</tr>
</thead>
<tbody>

{% for t in tag_list %}
<tr>
    {% if user.is_authenticated %}
        <td>
            <a href="/admin/hr/tag/{{ t.id }}/">Edit</a>
        </td>
    {% endif %}
    <td class="tag_col"><a href="{{ t.get_absolute_url }}">{{ t.name }}</a></th>
    <td>
        {% if not t.book_set.count %}&nbsp;{% endif %}
        {% for b in t.book_set.all %}
        {% if not forloop.first %}/{% endif %}
            <a href="{{ b.get_absolute_url }}">{{ b.title }}</a> 
        {% endfor %}
    </td>
</tr>
{% endfor %}
</tbody>
</table>

{% include "frag_next_prev.html" %}
{% endblock %}